import { BOOTH_TEMPLATES } from "./templates";

export const TEMPLATE_ASSETS = [
  "about-you.jpg",
  "analog-music.jpg",
  "black-music-collage.jpg",
  "black-white-star-strip.jpg",
  "black-white-stars.jpg",
  "blue-camera-collage.jpg",
  "blue-floral.jpg",
  "blue-notebook-memories.jpg",
  "burgundy-lace-frames.jpg",
  "burgundy-photo-strip.jpg",
  "classic-love-collage.jpg",
  "classic-red-polaroids.jpg",
  "comic-pop.jpg",
  "cute-fruit-polaroids.jpg",
  "cute-sticker-album.jpg",
  "denim-memories.jpg",
  "dreamy-vinyl.jpg",
  "fox-bunny-polaroids.jpg",
  "green-memories.jpg",
  "handmade-doodle.jpg",
  "japanese-retro-frames.jpg",
  "leopard-contact-sheet-4.jpg",
  "leopard-contact-sheet.jpg",
  "leopard-lace.jpg",
  "love-story-editorial.jpg",
  "midnight-polaroids.jpg",
  "pastel-camera-roll.jpg",
  "pastel-captured-moments.jpg",
  "picnic-memories.jpg",
  "pink-bow-memories.jpg",
  "pink-camera-gingham.jpg",
  "pink-cd.jpg",
  "pink-lace-bow-frames.jpg",
  "pink-quote-strip.jpg",
  "pink-spider-pop.jpg",
  "red-camera-collage.jpg",
  "red-gingham-camera.jpg",
  "red-gingham-film.jpg",
  "red-love-note.jpg",
  "retro-pinboard.jpg",
  "retro-red-camera.jpg",
  "retro-sun.jpg",
  "spider-man-music.jpg",
  "spotify-locker-strip.jpg",
  "swan-memories.jpg",
  "three-photo-collage.jpg",
  "vintage-lace-frames-2.jpg",
  "vintage-lace.jpg",
  "y2k-retro-camera.jpg",
] as const;

export type TemplateAsset = (typeof TEMPLATE_ASSETS)[number];

export const TEMPLATE_ASSET_MAP: Record<string, TemplateAsset> = {
  "classic-love-collage": "classic-love-collage.jpg",
  "pink-bow-memories": "pink-bow-memories.jpg",
  "red-love-note": "red-love-note.jpg",
  "vintage-lace": "vintage-lace.jpg",
  "retro-polaroid": "three-photo-collage.jpg",
  "classic-red-polaroids": "classic-red-polaroids.jpg",
  "blue-floral": "blue-floral.jpg",
  "pink-cd": "pink-cd.jpg",
  "black-white-stars": "black-white-stars.jpg",
  "vintage-film-strip": "burgundy-photo-strip.jpg",
  "blue-retro-camera": "y2k-retro-camera.jpg",
  "green-memories": "green-memories.jpg",
  "picnic-memories": "picnic-memories.jpg",
  "pink-green-childhood": "pink-lace-bow-frames.jpg",
  "handmade-doodle": "handmade-doodle.jpg",
  "simple-pink-frames": "pink-quote-strip.jpg",
  "retro-sun": "retro-sun.jpg",
  "travel-scrapbook": "blue-notebook-memories.jpg",
  "leopard-lace": "leopard-lace.jpg",
  "leopard-contact-sheet": "leopard-contact-sheet-4.jpg",
  "red-record-player": "red-camera-collage.jpg",
  "cherry-camera": "pink-camera-gingham.jpg",
  "black-music-collage": "black-music-collage.jpg",
  "pink-music-diary": "spotify-locker-strip.jpg",
  "swan-memories": "swan-memories.jpg",
  "blue-camera-collage": "blue-camera-collage.jpg",
  "pinboard-memories": "retro-pinboard.jpg",
  "retro-tv-frames": "retro-red-camera.jpg",
  "pastel-camera-roll": "pastel-camera-roll.jpg",
  "floral-polaroid-stack": "vintage-lace-frames-2.jpg",
  "red-gingham-camera": "red-gingham-camera.jpg",
  "cute-sticker-album": "cute-sticker-album.jpg",
  "love-story-editorial": "love-story-editorial.jpg",
  "about-you": "about-you.jpg",
  "retro-tv-stack": "burgundy-lace-frames.jpg",
  "japanese-retro-camera": "japanese-retro-frames.jpg",
  "midnight-romance": "midnight-polaroids.jpg",
  "analog-music": "analog-music.jpg",
  "dreamy-vinyl": "dreamy-vinyl.jpg",
  "retro-pinboard": "denim-memories.jpg",
  "y2k-pop-collage": "pink-spider-pop.jpg",
  "comic-pop": "comic-pop.jpg",
};

export function getTemplateAsset(id: string): string {
  return `/templates/${TEMPLATE_ASSET_MAP[id] ?? "classic-love-collage.jpg"}`;
}

export function getAllTemplateAssets() {
  return TEMPLATE_ASSETS.map((asset) => ({
    asset,
    src: `/templates/${asset}`,
    isMapped: Object.values(TEMPLATE_ASSET_MAP).includes(asset),
    templateId: Object.entries(TEMPLATE_ASSET_MAP).find(([, value]) => value === asset)?.[0] ?? null,
    templateName: Object.entries(TEMPLATE_ASSET_MAP).find(([key, value]) => value === asset && BOOTH_TEMPLATES.some(([id]) => id === key))?.[0] ?? null,
  }));
}
